x86: Fix invokevirtual and invokeinterface for missing methods
We need to throw NoSuchMethodError exception if a method does not exist.

Signed-off-by: Pekka Enberg <penberg@kernel.org>