runtime: Fix missing include
Fixes the following GCC warning:

    CC       runtime/reflection.o
  runtime/reflection.c: In function ‘java_lang_reflect_VMMethod_getParameterAnnotations’:
  runtime/reflection.c:1296:4: warning: implicit declaration of function ‘vm_annotation_to_object’
  runtime/reflection.c:1296:4: warning: nested extern declaration of ‘vm_annotation_to_object’
  runtime/reflection.c:1296:15: warning: assignment makes pointer from integer without a cast

Signed-off-by: Pekka Enberg <penberg@kernel.org>