jit: Fix missing include in jit/gdb.c
This patch fixes the following compilation warning:

  jit/gdb.c: In function ‘gdb_register_method’:
  jit/gdb.c:151: warning: implicit declaration of function ‘sprintf’
  jit/gdb.c:151: warning: incompatible implicit declaration of built-in function ‘sprintf’
  jit/gdb.c: In function ‘gdb_register_trampoline’:
  jit/gdb.c:166: warning: incompatible implicit declaration of built-in function ‘sprintf’

Signed-off-by: Pekka Enberg <penberg@kernel.org>