x86: better definition of REG_UNASSIGNED
Standard C enums are 'int'-typed. On x86-64, GCC complains about defining
REG_UNASSIGNED as equal to ~0UL, because sizeof(unsigned long) >
sizeof(int) and the resulting value exceeds the allowed range. The actual
error is:

error: specified mode too small for enumeral values

Signed-off-by: Eduard - Gabriel Munteanu <eduard.munteanu@linux360.ro>
Signed-off-by: Pekka Enberg <penberg@cs.helsinki.fi>