x86-64: Fix invokestatic for missing methods
Fix the instruction selector rule for invokestatic to properly handle
missing methods. The NoSuchMethodErrorTest test case is not enabled due
to unrelated problems that cause it to hang indefinitely while compiling
the test method for invokevirtual.

Signed-off-by: Pekka Enberg <penberg@kernel.org>