jit: Add missing stdio.h include
Fixes the following GCC issued warnings:

    CC       jit/ostack-bc.o
  jit/object-bc.c: In function ‘class_name_to_array_name’:
  jit/object-bc.c:41: warning: implicit declaration of function ‘snprintf’
  jit/object-bc.c:41: warning: incompatible implicit declaration of built-in function ‘snprintf’
  jit/object-bc.c:43: warning: incompatible implicit declaration of built-in function ‘snprintf’

Signed-off-by: Pekka Enberg <penberg@kernel.org>