jit: Fail lazily for missing methods
This patch changes the JIT compiler to generate code to invoke a
NoSuchMethodError stub instead of crashing if it encounters a method that does
not exists.

This fixes the following crash when running JPC:

  penberg@jaguar:~/testing/jato$ jato -Xmx1g -jar JPCApplication.jar
  Jun 14, 2010 7:52:58 p.m. org.jpc.j2se.JPCApplication main
  INFO: Using configuration specified in manifest
  Jun 14, 2010 7:53:01 p.m. org.jpc.emulator.memory.codeblock.CodeBlockManager <init>
  INFO: JVM allows classloader creation: using advanced compilers.
  Header Chunk. Image width:50 height:50 depth:8 color type:6 compression type:0 filter type:0 interlace:0
  Header Chunk. Image width:50 height:50 depth:8 color type:6 compression type:0 filter type:0 interlace:0
  convert_invokestatic: warning: unable to resolve invocation target
  convert_instruction: warning: conversion error at PC=12791
  compile_error: error: Failed to compile method `fullExecute' in class `org/jpc/emulator/memory/codeblock/optimised/RealModeUBlock', error: -22 ('Invalid argument')
  [PC Execute] Native and Java stack trace:
  [PC Execute]  [<080799ab>] native     : do_error+26 (/home/penberg/src/jato/vm/die.c:29)
  [PC Execute]  [<0806a81c>] native     : jato(compile+0x240) [0x806a81c]
  [PC Execute]  [<08071969>] native     : jato(jit_magic_trampoline+0x13d) [0x8071969]
  [PC Execute]  [<a77a0cac>] trampoline : org/jpc/emulator/memory/codeblock/optimised/RealModeUBlock.fullExecute(RealModeUBlock.java:124)
  [PC Execute]  [<a78e93ba>] jit        : org/jpc/emulator/memory/codeblock/optimised/RealModeUBlock.execute(RealModeUBlock.java:1457)
  [PC Execute]  [<a78e811e>] jit        : org/jpc/emulator/memory/codeblock/AbstractCodeBlockWrapper.execute(AbstractCodeBlockWrapper.java:35)
  [PC Execute]  [<a78e80c8>] jit        : org/jpc/emulator/memory/codeblock/BackgroundCompiler$ExecuteCountingCodeBlockWrapper.execute(BackgroundCompiler.java:112)
  [PC Execute]  [<a78d29c7>] jit        : org/jpc/emulator/memory/LazyCodeBlockMemory.executeReal(LazyCodeBlockMemory.java:104)
  [PC Execute]  [<a78d2803>] jit        : org/jpc/emulator/memory/PhysicalAddressSpace.executeReal(PhysicalAddressSpace.java:288)
  [PC Execute]  [<a78d136e>] jit        : org/jpc/emulator/PC.executeReal(PC.java:385)
  [PC Execute]  [<a78d1252>] jit        : org/jpc/emulator/PC.execute(PC.java:371)
  [PC Execute]  [<a78d0565>] jit        : org/jpc/j2se/PCMonitorFrame.run(PCMonitorFrame.java:197)
  [PC Execute]  [<a771dc8d>] jit        : java/lang/Thread.run(Thread.java:745)
  [PC Execute]  [<a771d9c5>] jit        : java/lang/VMThread.run(VMThread.java:120)
  [PC Execute]  [<0805cea7>] native     : do_native_call+4f (/home/penberg/src/jato/arch/x86/call.c:43)
  [PC Execute]  [<0805cf3f>] native     : native_call+6e (/home/penberg/src/jato/arch/x86/call.c:119)
  [PC Execute]  [<08076fa7>] native     : call_method_a+37 (/home/penberg/src/jato/vm/call.c:54)
  [PC Execute]  [<080770b5>] native     : vm_call_method_v+8f (/home/penberg/src/jato/vm/call.c:71)
  [PC Execute]  [<080839b2>] native     : vm_call_method+18559 (/home/penberg/src/jato/include/vm/call.h:60)
  [PC Execute]  [<08083a0f>] native     : vm_thread_entry+57 (/home/penberg/src/jato/vm/thread.c:295)
  [PC Execute]  [<08091400>] native     : exception_check+28e17 (arch/x86/unwind_32.S:75)
  [PC Execute]  [<b77ca96d>] native     : exception_check+af762384 (arch/x86/unwind_32.S:75)
  [PC Execute]  [<b7598a4d>] native     : exception_check+af530464 (arch/x86/unwind_32.S:75)
  Aborted

Cc: Tomek Grabiec <tgrabiec@gmail.com>
Cc: Vegard Nossum <vegard.nossum@gmail.com>
Signed-off-by: Pekka Enberg <penberg@cs.helsinki.fi>