vm: Call java.lang.Class constructor in native_vmclassloader_defineclass()
We must call constructor to pass ProtectionDomain object.
Before this no constructor was called and no ProtectionDomain
was registered for the class. This caused that equinox could
not locate the installation directory:

java.lang.RuntimeException: Could not find framework
   at org.eclipse.equinox.launcher.Main.getBootPath(Main.java:816)
   at org.eclipse.equinox.launcher.Main.basicRun(Main.java:431)
   at org.eclipse.equinox.launcher.Main.run(Main.java:1173)
   at org.eclipse.equinox.launcher.Main.main(Main.java:1148)

Signed-off-by: Tomek Grabiec <tgrabiec@gmail.com>
Signed-off-by: Pekka Enberg <penberg@cs.helsinki.fi>