jit: add missing include to jit/spill-reload.c
This patch fixes the following compile warning during "make test":

    CC       ../../jit/spill-reload.o
  ../../jit/spill-reload.c: In function ‘insert_spill_insn’:
  ../../jit/spill-reload.c:48: warning: implicit declaration of function ‘get_spill_slot_32’
  ../../jit/spill-reload.c:48: warning: assignment makes pointer from integer without a cast

Signed-off-by: Pekka Enberg <penberg@cs.helsinki.fi>